/**
 * Envelope encryption for secrets that must be readable again — currently the
 * TOTP seed.
 *
 * A password is hashed because nothing ever needs it back. A TOTP secret is
 * different: the server recomputes codes from it on every sign-in, so it has to
 * be recoverable, and storing it in plaintext would make a database read
 * equivalent to holding the phone. Two factors would collapse into one against
 * exactly the attacker the second factor exists to stop.
 *
 * AES-256-GCM, which authenticates as well as encrypts. Without the tag, write
 * access to the row would let an attacker flip ciphertext bits and steer the
 * decrypted seed to a value they chose, and the second factor would then verify
 * against their own authenticator.
 */
import { createCipheriv, createDecipheriv, hkdfSync, randomBytes } from 'node:crypto';
import { WorkerError } from '@eiaaw/core';

const VERSION = 'v1';
const ALGORITHM = 'aes-256-gcm';
const KEY_BYTES = 32;

/** 96 bits is the GCM-native nonce size; anything else is rehashed internally. */
const IV_BYTES = 12;
const TAG_BYTES = 16;

/**
 * Short enough to be a passphrase someone typed is short enough to be guessed.
 * KMS_MASTER_KEY is generated by `scripts/generate-crypto-keys.mjs`, which
 * emits far more than this; the floor exists to catch a placeholder that
 * reached production.
 */
const MIN_MASTER_KEY_LENGTH = 32;

/**
 * HKDF with a per-purpose label, so one master key yields unrelated subkeys.
 * Using the master key directly for several purposes means a weakness in any
 * one use compromises all of them.
 */
export function deriveSealingKey(masterKey: string, purpose: string): Buffer {
  if (masterKey.length < MIN_MASTER_KEY_LENGTH) {
    throw new WorkerError('contract_invalid', {
      detail:
        `The sealing master key is ${String(masterKey.length)} characters; at least ` +
        `${String(MIN_MASTER_KEY_LENGTH)} are required. A value this short is a placeholder ` +
        'that reached production, not key material.',
      failureClass: 'configuration',
      retryable: false,
    });
  }

  return Buffer.from(
    hkdfSync(
      'sha256',
      Buffer.from(masterKey, 'utf8'),
      Buffer.alloc(0),
      `eiaaw:seal:${purpose}`,
      KEY_BYTES,
    ),
  );
}

/** `v1.<iv>.<tag>.<ciphertext>`, each part base64url. */
export function sealSecret(plaintext: string, key: Buffer): string {
  const iv = randomBytes(IV_BYTES);
  const cipher = createCipheriv(ALGORITHM, key, iv);
  const body = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();

  return [
    VERSION,
    iv.toString('base64url'),
    tag.toString('base64url'),
    body.toString('base64url'),
  ].join('.');
}

export function openSecret(sealed: string, key: Buffer): string {
  const parts = sealed.split('.');

  if (parts.length !== 4) {
    throw new WorkerError('internal_error', {
      detail:
        'A sealed secret is not in the expected four-part form and cannot be opened. ' +
        'The stored value is corrupt, which is a different problem from a wrong key.',
      failureClass: 'internal',
      retryable: false,
    });
  }

  const [version, ivPart, tagPart, bodyPart] = parts as [string, string, string, string];

  if (version !== VERSION) {
    throw new WorkerError('internal_error', {
      detail:
        `A sealed secret declares format "${version}", but this build only implements ` +
        `"${VERSION}". Refusing rather than attempting to open it under the wrong rules.`,
      failureClass: 'internal',
      retryable: false,
    });
  }

  const iv = Buffer.from(ivPart, 'base64url');
  const tag = Buffer.from(tagPart, 'base64url');

  if (iv.length !== IV_BYTES || tag.length !== TAG_BYTES) {
    throw new WorkerError('internal_error', {
      detail: 'A sealed secret carries a nonce or tag of the wrong length and cannot be opened.',
      failureClass: 'internal',
      retryable: false,
    });
  }

  try {
    const decipher = createDecipheriv(ALGORITHM, key, iv);
    decipher.setAuthTag(tag);
    return Buffer.concat([
      decipher.update(Buffer.from(bodyPart, 'base64url')),
      decipher.final(),
    ]).toString('utf8');
  } catch (cause) {
    // GCM does not distinguish a wrong key from altered ciphertext, and neither
    // should the message: both mean the value cannot be trusted.
    throw new WorkerError('internal_error', {
      detail:
        'A sealed secret failed authentication. Either it was sealed under a different ' +
        'key — a rotated KMS_MASTER_KEY without re-sealing — or the stored value was ' +
        'altered. It is not safe to use either way.',
      failureClass: 'internal',
      retryable: false,
      cause,
    });
  }
}
