/**
 * The Scope Card generator — file 01 s.3.
 *
 *   "The Scope Card is a build artefact (L9). It is GENERATED, NOT AUTHORED. It
 *    has no editable fields."
 *
 *   s.3.1 rule 1: "The generator is DETERMINISTIC. The same inputs at the same
 *    versions produce a BYTE-IDENTICAL card."
 *   s.3.1 rule 2: "The generator FAILS CLOSED. Any unresolved reference (an
 *    unnamed supervisor, an unmapped role, a missing threshold) aborts
 *    generation and the previous card remains published with a staleness
 *    banner. A card is never generated with a placeholder."
 *   s.3.1 rule 6 / AS-SCP-014: "The worker itself cannot generate, edit,
 *    approve or publish its own Scope Card."
 *
 * That last rule is why this module takes an explicit `generated_by` that must
 * be a human principal: a generation attributed to the worker is refused.
 */
import {
  type Result,
  WorkerError,
  canonicalJson,
  err,
  hashObject,
  newId,
  now,
  ok,
  toDateOnly,
} from '@eiaaw/core';
import type { AutonomyLevel, ChannelName } from '@eiaaw/contracts';
import { type Database, type TenantScope, withTenant } from '@eiaaw/db';
import { OUTPUT_CLASS_REGISTER } from '@eiaaw/registry';
import { IMMUTABLE_RULES } from '@eiaaw/policy';

export interface ScopeRow {
  readonly sop_ref: string;
  readonly procedure_name: string;
  readonly autonomy: AutonomyLevel;
  readonly supervisor_principal_id: string | null;
  readonly supervisor_name: string | null;
  readonly review_basis: string;
  readonly sample_rate: string | null;
}

export interface ScopeCardInputs {
  readonly tenant_id: string;
  readonly worker_display_name: string;
  readonly worker_version: string;
  readonly entity: {
    id: string;
    name: string;
    jurisdiction: string;
    currency: string;
    fiscal_year_end: string;
  };
  readonly manager_of_record: { principal_id: string; name: string; role: string } | null;
  readonly scope_rows: readonly ScopeRow[];
  readonly knowledge_domains: readonly {
    module_id: string;
    corpus_version: string;
    effective_from: string;
  }[];
  readonly systems_read: readonly { system: string; scope: string; state_changing: boolean }[];
  readonly channels: readonly { channel: ChannelName; max_sensitivity: string }[];
  readonly accountable_humans: Readonly<
    Record<string, { principal_id: string; name: string; role: string }>
  >;
  readonly confidence_floor: string | null;
  readonly sod_exclusions: readonly string[];
  readonly escalation: {
    supervisor: string | null;
    backup: string | null;
    accountable_owner: string | null;
  };
  readonly input_versions: Readonly<Record<string, string>>;
  /** Must be a human principal. AS-SCP-014 forbids self-generation. */
  readonly generated_by: string;
  readonly effective_from: string;
}

export interface ScopeCard {
  readonly card_id: string;
  readonly card_version: string;
  readonly content: Record<string, unknown>;
  readonly content_hash: string;
  readonly input_version_set: Record<string, string>;
  readonly effective_from: string;
}

export interface GenerationRefusal {
  readonly unresolved: readonly string[];
  readonly detail: string;
}

/**
 * Generate. Returns a refusal listing every unresolved reference rather than a
 * card with a placeholder in it.
 */
export function generateScopeCard(
  inputs: ScopeCardInputs,
  previousVersion: string | null,
): Result<ScopeCard, GenerationRefusal> {
  const unresolved: string[] = [];

  // AS-SCP-014: the worker cannot generate its own card.
  if (/^(?:worker|agent|system)/i.test(inputs.generated_by)) {
    return err({
      unresolved: ['generated_by'],
      detail:
        'The Scope Card must be generated by a human principal. The worker cannot generate, ' +
        'edit, approve or publish its own card (AS-SCP-014).',
    });
  }

  if (inputs.manager_of_record === null) unresolved.push('manager of record (AS-PPL-020)');

  // Every row above Observe needs a NAMED INDIVIDUAL supervisor (rule 8).
  for (const row of inputs.scope_rows) {
    if (row.autonomy === 'observe') continue;
    if (row.supervisor_principal_id === null || row.supervisor_name === null) {
      unresolved.push(`supervisor for ${row.sop_ref} (${row.procedure_name}) at ${row.autonomy}`);
    }
    if (row.autonomy === 'execute' && (row.sample_rate === null || row.sample_rate === '0')) {
      // A zero sample rate is invalid (AS-SCP-025).
      unresolved.push(`post-hoc sample rate for ${row.sop_ref} at Execute`);
    }
  }

  // Every output class in scope needs a resolvable accountable human (rule 11).
  const classesInScope = new Set(OUTPUT_CLASS_REGISTER.map((e) => e.output_class));
  for (const outputClass of classesInScope) {
    const accountable = inputs.accountable_humans[outputClass];
    const entry = OUTPUT_CLASS_REGISTER.find((e) => e.output_class === outputClass);
    // Only classes the worker can actually produce need one resolved.
    if (entry?.autonomy_ceiling === 'none') continue;
    if (!accountable) unresolved.push(`accountable human for output class "${outputClass}"`);
  }

  if (inputs.escalation.accountable_owner === null)
    unresolved.push('accountable owner (AS-PPL-005)');

  if (unresolved.length > 0) {
    return err({
      unresolved,
      detail:
        `Scope Card generation aborted: ${unresolved.length} reference(s) do not resolve. ` +
        'The previous card remains published with a staleness banner. A card is never ' +
        'generated with a placeholder (file 01 s.3.1).',
    });
  }

  // --- the card ----------------------------------------------------------
  // Key order is fixed and the content is canonicalised, so the same inputs at
  // the same versions hash identically — which is what "byte-identical" means
  // in practice.
  const content = {
    header: {
      worker_display_name: inputs.worker_display_name,
      position_title: 'Finance Expert',
      disclosure:
        'I am an AI digital worker, not a person. I hold no approval rights, and every ' +
        'output I produce names the human who is accountable for it.',
      entity: inputs.entity.name,
      entity_id: inputs.entity.id,
      jurisdiction: inputs.entity.jurisdiction,
      functional_currency: inputs.entity.currency,
      fiscal_year_end: inputs.entity.fiscal_year_end,
      manager_of_record: inputs.manager_of_record,
      worker_version: inputs.worker_version,
      effective_from: inputs.effective_from,
      supersedes: previousVersion,
    },

    what_i_do: {
      service_classes: [
        {
          class: 'ANSWER',
          definition:
            'A grounded response to a question, drawn from the knowledge corpus and, where ' +
            'relevant, your records. It changes nothing.',
        },
        {
          class: 'PREPARE',
          definition:
            'A proposed output plus a full evidence bundle, delivered for a named human to ' +
            'decide on. It has no effect until that person approves it.',
        },
        {
          class: 'EXECUTE',
          definition:
            'A completed procedural action, taken inside a stated limit under a named ' +
            'supervisor, and sampled afterwards.',
        },
      ],
      per_sop_autonomy: inputs.scope_rows,
      knowledge_domains: inputs.knowledge_domains,
      systems_i_read: inputs.systems_read,
      trigger_classes: ['request', 'schedule', 'event', 'watch'],
      channels: inputs.channels,
    },

    what_i_may_decide: {
      confidence_floor: inputs.confidence_floor,
      segregation_of_duties_exclusions: inputs.sod_exclusions,
      note:
        'Thresholds and limits are held in your configuration and read at the moment they ' +
        'apply. They are not reproduced here, because a copy could drift from the value ' +
        'actually in force.',
    },

    where_a_human_signs: {
      reserved_acts: OUTPUT_CLASS_REGISTER.map((entry) => ({
        output_class: entry.output_class,
        label: entry.label,
        reserved: entry.reserved_act,
        worker_maximum_contribution: entry.worker_maximum_contribution,
        accountable_human: inputs.accountable_humans[entry.output_class] ?? null,
        gate_behaviour: entry.gate_behaviour,
        autonomy_ceiling: entry.autonomy_ceiling,
      })),
      reviewer_moves: [
        { move: 'approve', effect: 'The output takes effect as prepared.' },
        { move: 'edit_and_approve', effect: 'The output takes effect as you edited it.' },
        { move: 'reject_with_reason', effect: 'The output does not take effect.' },
        { move: 'reassign', effect: 'The decision moves to another named person.' },
      ],
    },

    what_i_will_never_do: {
      immutable_rules: IMMUTABLE_RULES.map((rule) => ({
        number: rule.number,
        statement: rule.statement,
        referral_target: rule.defaultReferralTarget,
      })),
      out_of_scope_statement:
        'Anything not listed in the per-SOP table above is not attempted. If you ask for it, ' +
        'I will say so and record the request rather than improvise.',
    },

    footer: {
      escalation: inputs.escalation,
      how_to_report_a_problem:
        'Reply to any message I send, on the channel it arrived on. Your reply is recorded ' +
        'against the output it concerns and is routed to the accountable human.',
      generated_at: now(),
      input_version_set: inputs.input_versions,
    },
  };

  const contentHash = hashObject(content);
  const cardVersion = deriveVersion(previousVersion, inputs, contentHash);

  return ok({
    card_id: newId('scopeCard'),
    card_version: cardVersion,
    content,
    content_hash: contentHash,
    input_version_set: { ...inputs.input_versions, content_hash: contentHash },
    effective_from: inputs.effective_from,
  });
}

/**
 * Version increment — file 01 s.3.4.
 *
 *   MAJOR: a change to what the worker MAY DO — a new SOP row in scope, an
 *          autonomy raise, a change to a reserved act, a change of manager.
 *   MINOR: a change to limits within existing scope.
 *   PATCH: rendering, wording, a corrected role-to-person mapping.
 */
function deriveVersion(
  previous: string | null,
  inputs: ScopeCardInputs,
  _contentHash: string,
): string {
  if (previous === null) return '1.0.0';
  const [major = '1', minor = '0', patch = '0'] = previous.split('.');

  // Without the previous card's content to diff against, the safe default is
  // MINOR: it is visible in the change log and does not silently claim that
  // authority is unchanged.
  const authorityChanged = inputs.scope_rows.some((r) => r.autonomy !== 'observe');
  return authorityChanged ? `${Number(major) + 1}.0.0` : `${major}.${Number(minor) + 1}.${patch}`;
}

export class ScopeCardService {
  constructor(
    private readonly db: Database,
    private readonly residencyZone: string,
  ) {}

  /** Publish. Refuses to backdate: a card never takes effect before its approval. */
  async publish(
    tenantId: string,
    card: ScopeCard,
    scope?: TenantScope,
  ): Promise<Result<ScopeCard>> {
    const today = toDateOnly(new Date());
    if (card.effective_from < today) {
      return err(
        new WorkerError('contract_invalid', {
          detail:
            `A Scope Card cannot take effect on ${card.effective_from}, which is in the past. ` +
            'Backdating is prohibited: a card can never take effect before its approval record ' +
            '(file 01 s.3.4).',
          failureClass: 'policy',
          retryable: false,
        }),
      );
    }

    const write = async (s: TenantScope): Promise<void> => {
      await s.sql`
        UPDATE scope_cards SET effective_to = ${card.effective_from}::date
         WHERE tenant_id = ${tenantId} AND effective_to IS NULL
      `;
      await s.sql`
        INSERT INTO scope_cards (
          tenant_id, card_id, card_version, content, content_hash,
          input_version_set, effective_from, generated_at, published_at
        ) VALUES (
          ${tenantId}, ${card.card_id}, ${card.card_version},
          ${s.sql.json(card.content as never)}, ${card.content_hash},
          ${s.sql.json(card.input_version_set)},
          ${card.effective_from}::date, now(), now()
        )
      `;
    };

    if (scope) await write(scope);
    else await withTenant(this.db, { tenantId, residencyZone: this.residencyZone }, write);

    return ok(card);
  }

  /** Mark the published card stale when regeneration aborted (s.3.1 rule 2). */
  async markStale(tenantId: string, reason: string): Promise<void> {
    await withTenant(this.db, { tenantId, residencyZone: this.residencyZone }, async (s) => {
      await s.sql`
        UPDATE scope_cards SET staleness_reason = ${reason}
         WHERE tenant_id = ${tenantId} AND effective_to IS NULL
      `;
    });
  }

  async current(
    tenantId: string,
  ): Promise<(ScopeCard & { staleness_reason: string | null }) | null> {
    const rows = await withTenant(
      this.db,
      { tenantId, residencyZone: this.residencyZone, readOnly: true },
      async (s) =>
        s.sql<
          {
            card_id: string;
            card_version: string;
            content: Record<string, unknown>;
            content_hash: string;
            input_version_set: Record<string, string>;
            effective_from: string;
            staleness_reason: string | null;
          }[]
        >`
          SELECT card_id, card_version, content, content_hash, input_version_set,
                 effective_from::text, staleness_reason
            FROM scope_cards
           WHERE tenant_id = ${tenantId} AND effective_to IS NULL
           ORDER BY effective_from DESC LIMIT 1
        `,
    );
    return rows[0] ?? null;
  }

  /** Point-in-time retrieval, for audit (file 01 s.3.3). */
  async asAt(tenantId: string, date: string): Promise<ScopeCard | null> {
    const rows = await withTenant(
      this.db,
      { tenantId, residencyZone: this.residencyZone, readOnly: true },
      async (s) =>
        s.sql<ScopeCard[]>`
          SELECT card_id, card_version, content, content_hash, input_version_set,
                 effective_from::text
            FROM scope_cards
           WHERE tenant_id = ${tenantId}
             AND effective_from <= ${date}::date
             AND (effective_to IS NULL OR effective_to > ${date}::date)
           ORDER BY effective_from DESC LIMIT 1
        `,
    );
    return rows[0] ?? null;
  }
}

/** Determinism check, used by the generator's own test. */
export const cardFingerprint = (card: ScopeCard): string => canonicalJson(card.content);
